### PR TITLE
Fixture. Earlier versions of Fritz!OS do not support AIN parameter wi…

### PR DESCRIPTION
**Pull request by mwittig**
…th getDeviceListInfo service method. This getDeviceListInfo may return a list of device info objects

### CODE REVIEW

**Comment by andig** [comment]
Shouldnt this rather go into the smartfritz library?

**Comment by mwittig** [comment]
Well, possibly. I think we can do this later. It's just five lines of code anyway. Let me have a word with AVM first to get a better understanding of the interface specification. In my opinion the document is not very good and needs clarification. The interface is also not well designed as it lacks versioning to handle the difference behavior of the service with the different Fritz!OS versions.

**Comment by andig** [comment]
> Let me have a word with AVM first to get a better understanding of the interface specification. 

Much appreciated. 

Please note: due to the merge reverses I also can't merge any of your changes at this time. While the merge content has been undone, the commits are still in the history (for an explanation see ftp://www.kernel.org/pub/software/scm/git/docs/howto/revert-a-faulty-merge.txt).
To move forward I'd suggest to stash all your changed, create a new branch off master and apply the stashed changes. From there on PRs will be mergeable again.

**Comment by mwittig** [comment]
@andig Ok, I'll prepare a new PR tomorrow.

**Pull request closed without merging**
