### PR TITLE
Suggested implementation for temperature feature (issue #2). 

### PR DESCRIPTION
**Pull request by mwittig**
- Implemented temperature readings using "getdevicelistinfos" service method ([issue #2](https://github.com/andig/pimatic-fritz/issues/2)) - see http://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/AHA-HTTP-Interface.pdf
- Added support for xAttributionOptions and xLink extensions.

### CODE REVIEW

**Comment by andig** [comment]
I like it. However- are you entirely sure the XML API is as widely support by all Fritz Boxes as the current api?

**Comment by andig** [comment]
Just saw your other message.

**Comment by mwittig** [comment]
According to Interface-Doumentation the XML API is supported since  FRITZ!OS 6.00. If a device is missing a feature (e.g. Fritz!Dect 200 with old firmware) this is also handled gracefully by the code.

**Comment by andig** [comment]
@mwittig could you take a look at #7? I'm suspecting this may be caused by this pr?

**Comment by mwittig** [comment]
@andig  OK, will do

**Pull request merged**
